=== cropsinsilico/yggdrasil/_downloads/cc04e0fe2c9526da71ddd77755fcaf65/metaschema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "default": {},
    "definitions": {
        "positiveInteger": {
            "minimum": 0,
            "type": "integer"
        },
        "positiveIntegerDefault0": {
            "allOf": [
                {
                    "$ref": "#/definitions/positiveInteger"
                },
                {
                    "default": 0
                }
            ]
        },
        "schemaArray": {
            "items": {
                "$ref": "#"
            },
            "minItems": 1,
            "type": "array"
        },
        "simpleTypes": {
            "enum": [
                "array",
                "boolean",
                "integer",
                "null",
                "number",
                "object",
                "string",
                "1darray",
                "any",
                "bytes",
                "class",
                "complex",
                "float",
                "function",
                "instance",
                "int",
                "ndarray",
                "obj",
                "ply",
                "scalar",
                "schema",
                "uint",
                "unicode"
            ]
        },
        "stringArray": {
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
        }
    },
    "dependencies": {
        "exclusiveMaximum": [
            "maximum"
        ],
        "exclusiveMinimum": [
            "minimum"
        ]
    },
    "description": "Core schema meta-schema",
    "id": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "$schema": {
            "format": "uri",
            "type": "string"
        },
        "additionalItems": {
            "anyOf": [
                {
                    "type": "boolean"
                },
                {
                    "$ref": "#"
                }
            ],
            "default": {}
        },
        "additionalProperties": {
            "anyOf": [
                {
                    "type": "boolean"
                },
                {
                    "$ref": "#"
                }
            ],
            "default": {}
        },
        "allOf": {
            "$ref": "#/definitions/schemaArray"
        },
        "anyOf": {
            "$ref": "#/definitions/schemaArray"
        },
        "args": {
            "description": "Arguments required to recreate a class instance.",
            "type": "array"
        },
        "class": {
            "anyOf": [
                {
                    "type": "class"
                },
                {
                    "items": {
                        "type": "class"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ],
            "description": "One or more classes that the object should be an instance of."
        },
        "default": {},
        "definitions": {
            "additionalProperties": {
                "$ref": "#"
            },
            "default": {},
            "type": "object"
        },
        "dependencies": {
            "additionalProperties": {
                "anyOf": [
                    {
                        "$ref": "#"
                    },
                    {
                        "$ref": "#/definitions/stringArray"
                    }
                ]
            },
            "type": "object"
        },
        "description": {
            "type": "string"
        },
        "enum": {
            "type": "array"
        },
        "exclusiveMaximum": {
            "default": false,
            "type": "boolean"
        },
        "exclusiveMinimum": {
            "default": false,
            "type": "boolean"
        },
        "format": {
            "type": "string"
        },
        "id": {
            "format": "uri",
            "type": "string"
        },
        "items": {
            "anyOf": [
                {
                    "$ref": "#"
                },
                {
                    "$ref": "#/definitions/schemaArray"
                }
            ],
            "default": {}
        },
        "kwargs": {
            "description": "Keyword arguments required to recreate a class instance.",
            "type": "object"
        },
        "length": {
            "description": "Number of elements in the 1D array.",
            "minimum": 1,
            "type": "number"
        },
        "maxItems": {
            "$ref": "#/definitions/positiveInteger"
        },
        "maxLength": {
            "$ref": "#/definitions/positiveInteger"
        },
        "maxProperties": {
            "$ref": "#/definitions/positiveInteger"
        },
        "maximum": {
            "type": "number"
        },
        "minItems": {
            "$ref": "#/definitions/positiveIntegerDefault0"
        },
        "minLength": {
            "$ref": "#/definitions/positiveIntegerDefault0"
        },
        "minProperties": {
            "$ref": "#/definitions/positiveIntegerDefault0"
        },
        "minimum": {
            "type": "number"
        },
        "multipleOf": {
            "exclusiveMinimum": true,
            "minimum": 0,
            "type": "number"
        },
        "not": {
            "$ref": "#"
        },
        "oneOf": {
            "$ref": "#/definitions/schemaArray"
        },
        "pattern": {
            "format": "regex",
            "type": "string"
        },
        "patternProperties": {
            "additionalProperties": {
                "$ref": "#"
            },
            "default": {},
            "type": "object"
        },
        "precision": {
            "description": "The size (in bits) of each item.",
            "minimum": 1,
            "type": "number"
        },
        "properties": {
            "additionalProperties": {
                "$ref": "#"
            },
            "default": {},
            "type": "object"
        },
        "required": {
            "$ref": "#/definitions/stringArray"
        },
        "shape": {
            "description": "Shape of the ND array in each dimension.",
            "items": {
                "minimum": 1,
                "type": "integer"
            },
            "type": "array"
        },
        "subtype": {
            "description": "The base type for each item.",
            "enum": [
                "bytes",
                "complex",
                "float",
                "int",
                "uint",
                "unicode"
            ],
            "type": "string"
        },
        "temptype": {
            "description": "The type of the data for a single message.",
            "type": "schema"
        },
        "title": {
            "type": "string"
        },
        "type": {
            "anyOf": [
                {
                    "$ref": "#/definitions/simpleTypes"
                },
                {
                    "items": {
                        "$ref": "#/definitions/simpleTypes"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "uniqueItems": {
            "default": false,
            "type": "boolean"
        },
        "units": {
            "description": "Physical units.",
            "type": "string"
        }
    },
    "title": "Ygg meta-schema for data type schemas",
    "type": "object"
}

=== cropsinsilico/yggdrasil/_downloads/c21d4c7a20141976962eb50eca4ce149/model_form.json
{
    "title": "Model YAML Schema",
    "description": "Schema for yggdrasil model YAML input files.",
    "type": "object",
    "definitions": {
        "comm": {
            "description": "Base schema for all subtypes of comm components.",
            "additionalProperties": false,
            "dependencies": {
                "driver": [
                    "args"
                ]
            },
            "properties": {
                "commtype": {
                    "default": "default",
                    "description": "Communication mechanism that should be used.",
                    "enum": [
                        "buffer",
                        "default",
                        "ipc",
                        "mpi",
                        "rest",
                        "rmq",
                        "rmq_async",
                        "value",
                        "zmq"
                    ],
                    "type": "string"
                },
                "datatype": {
                    "$ref": "#/definitions/schema"
                },
                "default_file": {
                    "$ref": "#/definitions/file"
                },
                "default_value": {
                    "description": "Value that should be returned in the event that a yaml does not pair the comm with another model comm or a file.",
                    "type": "any"
                },
                "filter": {
                    "$ref": "#/definitions/filter",
                    "description": "Filter that will be used to determine when messages should be sent/received. Ignored if not provided."
                },
                "format_str": {
                    "description": "String that should be used to format/parse messages. Default to None.",
                    "type": "string"
                },
                "name": {
                    "description": "Name used for component in log messages.",
                    "type": "string"
                },
                "outside_loop": {
                    "default": false,
                    "description": "If True, and the comm is an input/outputs to/from a model being wrapped. The receive/send calls for this comm will be outside the loop for the model. Defaults to False.",
                    "type": "boolean",
                    "format": "checkbox"
                },
                "transform": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/transform"
                    },
                    "description": "One or more transformations that will be applied to messages that are sent/received. Ignored if not provided."
                },
                "vars": {
                    "description": "Names of variables to be sent/received by this comm. Defaults to [].",
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "count": {
                    "default": 1,
                    "type": "integer",
                    "options": {
                        "dependencies": {
                            "commtype": [
                                "value"
                            ]
                        }
                    }
                }
            },
            "required": [
                "datatype",
                "name",
                "commtype"
            ],
            "type": "object"
        },
        "file": {
            "description": "Base schema for all subtypes of file components.",
            "additionalProperties": false,
            "dependencies": {
                "driver": [
                    "args"
                ]
            },
            "properties": {
                "append": {
                    "default": false,
                    "description": "If True and writing, file is openned in append mode. If True and reading, file is kept open even if the end of the file is reached to allow for another process to write to the file in append mode. Defaults to False.",
                    "type": "boolean",
                    "format": "checkbox"
                },
                "filetype": {
                    "default": "binary",
                    "description": "The type of file that will be read from or written to.",
                    "enum": [
                        "ascii",
                        "binary",
                        "json",
                        "map",
                        "mat",
                        "netcdf",
                        "obj",
                        "pandas",
                        "pickle",
                        "ply",
                        "table",
                        "wofost",
                        "yaml"
                    ],
                    "type": "string"
                },
                "filter": {
                    "$ref": "#/definitions/filter",
                    "description": "Filter that will be used to determine when messages should be sent/received. Ignored if not provided."
                },
                "format_str": {
                    "description": "String that should be used to format/parse messages. Default to None.",
                    "type": "string"
                },
                "is_series": {
                    "default": false,
                    "description": "If True, input/output will be done to a series of files. If reading, each file will be processed until the end is reached. If writing, each output will be to a new file in the series. The addressed is assumed to contain a format for the index of the file. Defaults to False.",
                    "type": "boolean",
                    "format": "checkbox"
                },
                "name": {
                    "description": "Name used for component in log messages.",
                    "type": "string"
                },
                "transform": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/transform"
                        },
                        {
                            "type": "string"
                        },
                        {
                            "items": {
                                "anyOf": [
                                    {
                                        "$ref": "#/definitions/transform"
                                    },
                                    {
                                        "type": "string"
                                    }
                                ]
                            },
                            "type": "array"
                        }
                    ],
                    "description": "One or more transformations that will be applied to messages that are sent/received. Ignored if not provided."
                },
                "vars": {
                    "description": "Names of variables to be sent/received by this comm. Defaults to [].",
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "comment": {
                    "default": "# ",
                    "description": "One or more characters indicating a comment. Defaults to '# '.",
                    "type": "string",
                    "options": {
                        "dependencies": {
                            "filetype": [
                                "map",
                                "ply",
                                "netcdf",
                                "wofost",
                                "table",
                                "mat",
                                "ascii",
                                "pandas",
                                "obj",
                                "yaml",
                                "json",
                                "pickle"
                            ]
                        }
                    }
                },
                "delimiter": {
                    "default": "\t",
                    "description": "Delimiter that should be used to separate name/value pairs in the map. Defaults to \\t.",
                    "type": "string",
                    "options": {
                        "dependencies": {
                            "filetype": [
                                "map",
                                "wofost",
                                "table",
                                "pandas"
                            ]
                        }
                    }
                },
                "newline": {
                    "default": "\n",
                    "description": "One or more characters indicating a newline. Defaults to '\\n'.",
                    "type": "string",
                    "options": {
                        "dependencies": {
                            "filetype": [
                                "map",
                                "ply",
                                "netcdf",
                                "wofost",
                                "table",
                                "mat",
                                "ascii",
                                "pandas",
                                "obj",
                                "yaml",
                                "json",
                                "pickle"
                            ]
                        }
                    }
                },
                "read_attributes": {
                    "default": false,
                    "description": "If True, the attributes are read in as well as the variables. Defaults to False.",
                    "type": "boolean",
                    "options": {
